name: Notifications

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]
  release:
    types: [published]

jobs:
  send-notification:
    name: Send Notification
    runs-on: ubuntu-latest

    steps:
    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        channel: 'general'
        message: |
          New activity in repository:
          - Event: ${{ github.event_name }}
          - Repository: ${{ github.repository }}
          - Action by: ${{ github.actor }}
