name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Create Release Version
      id: create_version
      run: |
        version=$(jq -r '.version' < package.json)
        echo "New version: $version"
        echo "version=$version" >> $$GITHUB_OUTPUT

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.create_version.outputs.version }}
        name: Release ${{ steps.create_version.outputs.version }}
        body: |
          ## Changes
          - Update README.md
        draft: false
        prerelease: beta
